theme: minima
title: DemistyfAI
author: Tomasz Gusciora (still figuring out how to do Polish acute accents) 
description: All rights reserved. All presented views & statements are solely my own. For more legal mumbo-jumbo - please read "Disclaimers" post.