theme: minima
title: AnalyzeYou
author: Tomasz Gusciora (yaml doesn't support polish acute accents)
description: All rights reserved. Wszelkie prawa zastrzezone. 

Good luck pronouncing or remembering my last name ;)