theme: minima
title: DemistyfAI
author: Tomasz Gusciora (still figuring out how to support polish acute accents in this website template)
description: All rights reserved. All presented views & statements are solely my own. Site contents do not reflect views of any particular employer or business associate of mine. For more details - please read "Disclaimers" post.