theme: minima
title: AnalyzeYou
author: Tomasz Gusciora (still figuring out how to support polish acute accents in this website template)
description: All rights reserved. All presented vievs & statements are my personal and do not reflect any particular employers or business associates of mine.