theme: minima
title: AnalyzeYou
author: Tomasz Gusciora (still figuring out how to support polish acute accents in this website template)
description: All rights reserved. All statements & views here are my personal and cannot be associated with any particular employer or business associate of mine.