theme: minima
title: DemistyfAI
author: Tomasz Gusciora (still figuring out how to display Polish acute accents in this section) 
description: All rights reserved. All presented views & statements are solely my own. For more legal mumbo-jumbo - please read "Disclaimers" post.